### ISSUE TITLE
GEO-Microsoft Planetary Computer Programme RFP?

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/wallace-rmd#1]
Can we propose expanding on this prototype for the [GEO-Microsoft Planetary Computer Programme RFP](https://www.earthobservations.org/geo_blog_obs.php?id=503)? The RFP would provide 60k$ for salaries and 60k$ in compute credits. The RFP specifically mentions combining satellite data with biodiversity data from GBIF so I think it is a great fit.

We would need to put something together ASAP.

More links:

* [Planetary computer data catalog](https://planetarycomputer.microsoft.com/catalog)

I don't have the bandwidth to take the lead on this but I think it is a great opportunity and I want to help us leverage it if we can.

**Comment by 7yl4r** [comment]
@hart2 : what do you think?

**Comment by hart2** [comment]
@7yl4r : It's a possibility, but I don't know how likely. While my data did come through GBIF into OBIS, the combo of satellite and in situ data I use is from Bio-ORACLE. If we create an extra project which uses higher resolution data of landsat or sentinel, then we could focus on particular clusters of bird biodiversity data. Most data is found along the east and west coast of the US. I'm fairly unfamiliar with Microsoft Azure and the GEO-Microsoft Planetary Computer. What exactly would you want me to contribute?

**Comment by 7yl4r** [comment]
Mostly I think @bbest and I are looking for someone who wants to lead the science & research question part of this work. Ben may have some other contacts he might reach out to regarding this. 

Until I hear otherwise I am taking this off my todo list and we can close the issue once we have fully given up on pursuing the RFP.
